export enum ATokenEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
  OwnershipTransferred = 'OwnershipTransferred',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}

export enum BalanceViewerEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
  OwnershipTransferred = 'OwnershipTransferred',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
}

export enum DiaOracleEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  OwnershipTransferred = 'OwnershipTransferred',
  UpdaterChanged = 'UpdaterChanged',
  TokenPriceChanged = 'TokenPriceChanged',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
}

export enum FeeReductionProviderMockEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  OwnershipTransferred = 'OwnershipTransferred',
  Transfer = 'Transfer',
  Approval = 'Approval',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}

export enum FlashLoanReceiverMockEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  ExecutedWithSuccess = 'ExecutedWithSuccess',
  ExecutedWithFail = 'ExecutedWithFail',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
  OwnershipTransferred = 'OwnershipTransferred',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
}

export enum LendingPoolEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  OwnershipTransferred = 'OwnershipTransferred',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
}

export enum PriceFeedProviderEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  OwnershipTransferred = 'OwnershipTransferred',
  Transfer = 'Transfer',
  Approval = 'Approval',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}

export enum Psp22EmitableEvent {
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
  OwnershipTransferred = 'OwnershipTransferred',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}

export enum Psp22ForAuditEvent {
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
  OwnershipTransferred = 'OwnershipTransferred',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}

export enum Psp22OwnableEvent {
  OwnershipTransferred = 'OwnershipTransferred',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
  Transfer = 'Transfer',
  Approval = 'Approval',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
}

export enum StableTokenEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  Transfer = 'Transfer',
  Approval = 'Approval',
  OwnershipTransferred = 'OwnershipTransferred',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}

export enum TestReservesMinterEvent {
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  OwnershipTransferred = 'OwnershipTransferred',
  Transfer = 'Transfer',
  Approval = 'Approval',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}

export enum VTokenEvent {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
  MarketRuleChosen = 'MarketRuleChosen',
  CollateralSet = 'CollateralSet',
  Borrow = 'Borrow',
  Repay = 'Repay',
  FlashLoan = 'FlashLoan',
  Liquidation = 'Liquidation',
  InterestsAccumulated = 'InterestsAccumulated',
  AssetRegistered = 'AssetRegistered',
  PriceFeedProviderChanged = 'PriceFeedProviderChanged',
  FeeReductionChanged = 'FeeReductionChanged',
  FlashLoanFeeChanged = 'FlashLoanFeeChanged',
  ReserveActivated = 'ReserveActivated',
  ReserveFrozen = 'ReserveFrozen',
  ReserveInterestRateModelChanged = 'ReserveInterestRateModelChanged',
  ReserveRestrictionsChanged = 'ReserveRestrictionsChanged',
  ReserveFeesChanged = 'ReserveFeesChanged',
  AssetRulesChanged = 'AssetRulesChanged',
  IncomeTaken = 'IncomeTaken',
  StablecoinDebtRateChanged = 'StablecoinDebtRateChanged',
  RoleAdminChanged = 'RoleAdminChanged',
  RoleGranted = 'RoleGranted',
  RoleRevoked = 'RoleRevoked',
  Transfer = 'Transfer',
  Approval = 'Approval',
  OwnershipTransferred = 'OwnershipTransferred',
  Paused = 'Paused',
  Unpaused = 'Unpaused',
}
export type AnyAbaxContractEvent =
  | ATokenEvent
  | BalanceViewerEvent
  | DiaOracleEvent
  | FeeReductionProviderMockEvent
  | FlashLoanReceiverMockEvent
  | LendingPoolEvent
  | PriceFeedProviderEvent
  | Psp22EmitableEvent
  | Psp22ForAuditEvent
  | Psp22OwnableEvent
  | StableTokenEvent
  | TestReservesMinterEvent
  | VTokenEvent;
export const ContractsEvents = {
  ATokenEvent,
  BalanceViewerEvent,
  DiaOracleEvent,
  FeeReductionProviderMockEvent,
  FlashLoanReceiverMockEvent,
  LendingPoolEvent,
  PriceFeedProviderEvent,
  Psp22EmitableEvent,
  Psp22ForAuditEvent,
  Psp22OwnableEvent,
  StableTokenEvent,
  TestReservesMinterEvent,
  VTokenEvent,
};
